name: chatsen
description: 3rd party client for Twitch
publish_to: 'none'
version: 1.1.97+97

environment:
  # sdk: ">=2.17.0-168.0.dev <3.0.0"
  sdk: '>=2.18.0-97.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.9.0
  # webview_cookie_manager: ^2.0.6
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  provider: ^6.1.2
  collection: ^1.18.0
  sliver_tools: ^0.2.12
  file_picker: ^8.1.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  chewie: ^1.8.5
  wakelock_plus: ^1.2.8
  filesize: ^2.0.1
  flutter_acrylic: ^1.1.4
  bitsdojo_window: ^0.1.6
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  window_manager: ^0.4.2
  win32: ^5.5.4
  ffi: ^2.1.3
  flutter_localized_locales: ^2.0.5
  webview_windows: ^0.4.0
  flutter_local_notifications: ^17.2.3
  cached_network_image: ^3.3.1
  webview_flutter_wkwebview: ^3.16.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.5 # flutter packages pub run build_runner build
  analyzer: ^5.13.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
